name: BodyBoost
description: "A new Flutter Fitness project. "
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  cupertino_icons: ^1.0.6 # Ensure this is the latest
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated to the latest version

flutter:
  uses-material-design: true

  assets:
    - images/Me.jpg
    - images/Hands-Clapping-Chaulk-Kettlebell.webp

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico/Pacifico-Regular.ttf
